POST http://localhost:3000/api/logements
Content-Type: application/json

{
  "images": ["image1.jpg", "image2.jpg"],
  "titre": "Appartement moderne",
  "description": "Description de l'appartement moderne.",
  "nom": "Appartement A",
  "nombreChambre": 2,
  "prix": 1000,
  "contact": "contact@example.com",
  "lieu": "Ville A"
}

GET http://localhost:3000/api/logements

GET http://localhost:3000/api/logements/{logementId}

PUT http://localhost:3000/api/logements/{logementId}
Content-Type: application/json

{
  "nombreChambre": 3,
  "prix": 1200
}

DELETE http://localhost:3000/api/logements/{logementId}
